# Generated by Django 4.1.3 on 2022-11-22 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matrona',
            fields=[
                ('id_usuario', models.AutoField(default=100, primary_key=True, serialize=False)),
                ('id_superior', models.IntegerField(null=True)),
                ('nombre', models.TextField(max_length=50)),
                ('paterno', models.TextField(max_length=50)),
                ('materno', models.TextField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matrona_Clinica',
            fields=[
                ('matrona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.matrona')),
            ],
            bases=('core.matrona',),
        ),
        migrations.CreateModel(
            name='Matrona_Coordinadora',
            fields=[
                ('matrona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.matrona')),
            ],
            bases=('core.matrona',),
        ),
    ]
